# Recipe in rattler-build format.
# See https://prefix-dev.github.io/rattler-build/latest/

context:
  # This sample uses the free demo version of FLIP Fluids. If you want to use the paid version you'll need to change
  # the sha256sum in the section below and the filepath in the build.sh script to match that version's naming.
  version: "1.8.4"

package:
  name: blender-flipfluids
  version: ${{ version }}

source:
  - if: linux
    then:
      url: file://archive_files/FLIP_Fluids_addon_1.8.4_demo_.2025-07-17.zip
      sha256: b11b520688f8e9042656d658cd87e1479cca0d804b14cf507a7cf0b1335684d9
      # By specifying this filename directly, we prevent the contents of the addon from being extracted.
      file_name: FLIP_Fluids_addon_1.8.4_demo_.2025-07-17.zip

build:
  number: 0
  # These build options for repackaging an application
  # https://prefix-dev.github.io/rattler-build/latest/build_options/#prefix-detection-replacement-options
  prefix_detection:
    ignore_binary_files: True
  # https://prefix-dev.github.io/rattler-build/latest/build_options/#dynamic-linking-configuration
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      - "**"

requirements:
  run:
    - blender 4.5.*

tests:
  - script:
    - blender --version
    - |
      echo "Creating test.py"
      cat <<EOF > test.py
      import bpy
      import sys
      addon_names = [addon.module for addon in bpy.context.preferences.addons]
      print("Installed addons:")
      for addon in addon_names:
          print(addon)
      if "flip_fluids_addon" in addon_names:
          print("The flip_fluids_addon addon was found!")
          sys.exit(0)
      else:
          print("ERROR: The flip_fluids_addon addon was not installed.")
          sys.exit(1)
      EOF
    - blender --background --python-exit-code 1 --python test.py

about:
  homepage: https://flipfluids.com/
  license: MIT AND GPL-3.0-only
  summary: The FLIP Fluids addon is a tool that helps you set up, run, and render liquid simulation effects.