#!/bin/bash
# Plugin Sync for Blender
# Downloads plugin files from S3, configures BLENDER_USER_SCRIPTS, and
# auto-enables discovered addons via a Blender startup script.
# Runs after all standard Blender env vars are set (zzz- prefix ensures
# lexicographic ordering).
#
# S3 convention: s3://<bucket>/<prefix>/plugins/<os>/blender/<version>/
# Generic path:  s3://<bucket>/<prefix>/plugins/generic/
#
# Required environment variables (set by the worker agent):
#   DEADLINE_JA_S3_BUCKET      - Job attachment S3 bucket name
#   DEADLINE_JA_ROOT_PREFIX    - Job attachment root prefix in the bucket
#   OPENJD_SESSION_WORKING_DIR - Session working directory path

# Skip if the required env vars aren't available (e.g. local testing without
# the worker agent, or the worker agent hasn't been updated yet).
if [ -z "${DEADLINE_JA_S3_BUCKET:-}" ] || [ -z "${BLENDER_VERSION:-}" ]; then
    echo "Plugin Sync: Skipping — DEADLINE_JA_S3_BUCKET or BLENDER_VERSION not set." >&2
    return 0 2>/dev/null || exit 0
fi

_SP_PREFIX="${DEADLINE_JA_ROOT_PREFIX:+${DEADLINE_JA_ROOT_PREFIX}/}"
_SP_OS="linux"
case "$(uname -s)" in
    MINGW*|MSYS*|CYGWIN*) _SP_OS="windows" ;;
esac

# Determine plugin download directory
_SP_PLUGIN_DIR="${OPENJD_SESSION_WORKING_DIR:-${TMPDIR:-/tmp}}/deadline-plugins/blender"
mkdir -p "$_SP_PLUGIN_DIR"

# Download generic plugins to the session working directory
_SP_GENERIC_DIR="${OPENJD_SESSION_WORKING_DIR:-${TMPDIR:-/tmp}}/deadline-plugins/generic"
_SP_GENERIC_SRC="s3://${DEADLINE_JA_S3_BUCKET}/${_SP_PREFIX}plugins/generic/"
if aws s3 ls "$_SP_GENERIC_SRC" >/dev/null 2>&1; then
    mkdir -p "$_SP_GENERIC_DIR"
    echo "Plugin Sync: Downloading generic plugins from $_SP_GENERIC_SRC" >&2
    aws s3 cp "$_SP_GENERIC_SRC" "$_SP_GENERIC_DIR/" --recursive --quiet 2>/dev/null || true
fi

# Download Blender-specific plugins
_SP_DCC_SRC="s3://${DEADLINE_JA_S3_BUCKET}/${_SP_PREFIX}plugins/${_SP_OS}/blender/${BLENDER_VERSION}/"
if aws s3 ls "$_SP_DCC_SRC" >/dev/null 2>&1; then
    echo "Plugin Sync: Downloading Blender plugins from $_SP_DCC_SRC" >&2
    aws s3 cp "$_SP_DCC_SRC" "$_SP_PLUGIN_DIR/" --recursive --quiet 2>/dev/null || true
fi

# Configure Blender to find the plugins via BLENDER_USER_SCRIPTS
# Blender scans $BLENDER_USER_SCRIPTS/addons/ for addon directories/files.
# We create the expected subdirectory structure.
if [ -d "$_SP_PLUGIN_DIR" ] && [ "$(ls -A "$_SP_PLUGIN_DIR" 2>/dev/null)" ]; then
    mkdir -p "$_SP_PLUGIN_DIR/addons"
    # Move any top-level .py or .zip files into addons/
    find "$_SP_PLUGIN_DIR" -maxdepth 1 -name '*.py' -o -name '*.zip' | while read -r f; do
        mv "$f" "$_SP_PLUGIN_DIR/addons/"
    done
    # Move any top-level directories (addon packages) into addons/
    find "$_SP_PLUGIN_DIR" -maxdepth 1 -mindepth 1 -type d ! -name addons ! -name startup | while read -r d; do
        _target="$_SP_PLUGIN_DIR/addons/$(basename "$d")"
        if [ -d "$_target" ]; then
            cp -rf "$d"/* "$_target"/ 2>/dev/null || true
            rm -rf "$d"
        else
            mv "$d" "$_SP_PLUGIN_DIR/addons/"
        fi
    done

    export BLENDER_USER_SCRIPTS="$_SP_PLUGIN_DIR"
    export _SP_PLUGIN_DIR
    echo "Plugin Sync: BLENDER_USER_SCRIPTS=$_SP_PLUGIN_DIR" >&2

    # --- Auto-enable discovered addons ---
    # Generate a Blender startup script that enables all addons found in the
    # addons/ directory. Blender runs scripts in startup/ automatically when
    # BLENDER_USER_SCRIPTS is set.
    #
    # This eliminates the need for customers to manually call
    # bpy.ops.preferences.addon_enable() in their job scripts.

    _SP_ADDONS_DIR="$_SP_PLUGIN_DIR/addons"
    _SP_STARTUP_DIR="$_SP_PLUGIN_DIR/startup"
    mkdir -p "$_SP_STARTUP_DIR"

    # Discover addon module names from directory names and .py files
    _SP_ADDON_LIST=""
    for _entry in "$_SP_ADDONS_DIR"/*/; do
        [ -d "$_entry" ] || continue
        _name="$(basename "$_entry")"
        [ -f "$_entry/__init__.py" ] || continue
        _SP_ADDON_LIST="${_SP_ADDON_LIST}    \"${_name}\",
"
        echo "Plugin Sync: Found addon package: $_name" >&2
    done
    for _entry in "$_SP_ADDONS_DIR"/*.py; do
        [ -f "$_entry" ] || continue
        _name="$(basename "$_entry" .py)"
        _SP_ADDON_LIST="${_SP_ADDON_LIST}    \"${_name}\",
"
        echo "Plugin Sync: Found addon script: $_name" >&2
    done

    if [ -n "$_SP_ADDON_LIST" ]; then
        cat > "$_SP_STARTUP_DIR/plugin_sync_auto_enable.py" << PYEOF
"""Plugin Sync: Auto-enable addons downloaded from S3.

This script is generated by the zzz-blender-plugins activate script
and runs automatically when Blender starts (via BLENDER_USER_SCRIPTS/startup/).
"""
import bpy
import addon_utils
import os

_ADDONS = [
${_SP_ADDON_LIST}]

def _auto_enable():
    for module_name in _ADDONS:
        addons_dir = os.path.join(os.environ.get("BLENDER_USER_SCRIPTS", ""), "addons")
        # Determine the install source: directory __init__.py or .zip
        init_path = os.path.join(addons_dir, module_name, "__init__.py")
        zip_path = os.path.join(addons_dir, module_name + ".zip")
        install_path = None
        if os.path.isfile(init_path):
            install_path = init_path
        elif os.path.isfile(zip_path):
            install_path = zip_path

        try:
            # Register the addon in Blender's preferences via addon_install.
            # This ensures addons that access their own preferences during
            # register() (e.g. FLIP Fluids) work correctly. Wrapped in
            # try/except because addon_install can fail if the context is
            # restricted or the file is invalid — in that case we still
            # proceed with enable() since the addon is already in the
            # BLENDER_USER_SCRIPTS/addons/ search path.
            if install_path:
                try:
                    bpy.ops.preferences.addon_install(filepath=install_path, overwrite=True)
                except Exception:
                    pass  # Not fatal — addon is already in the search path
            addon_utils.enable(module_name, default_set=True)
            print(f"Plugin Sync: Enabled addon '{module_name}'")
        except Exception as e:
            print(f"Plugin Sync: WARNING - Failed to enable addon '{module_name}': {e}")

_auto_enable()
PYEOF
        echo "Plugin Sync: Generated auto-enable startup script for $(echo "$_SP_ADDON_LIST" | wc -l) addon(s)" >&2
    fi

    unset _SP_ADDONS_DIR _SP_STARTUP_DIR _SP_ADDON_LIST _entry _name
else
    echo "Plugin Sync: No Blender plugins found, skipping." >&2
fi

# Clean up temp variables
unset _SP_PREFIX _SP_OS _SP_GENERIC_DIR _SP_GENERIC_SRC _SP_DCC_SRC
