context:
  name: "redshift"
  display_name: "Redshift"
  version: "2025.3.0_1665182561"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - path: /usr/redshift #the default redshift install path. Assumes redshift has been installed on this computer
  #- path: ../redshift_core.tar.gz #optionally use a tarball of the install path instead
    target_directory: redshift

build:
  number: 0
  prefix_detection:
    ignore_binary_files: True
  dynamic_linking:
    rpaths:
    - opt/houdini/dsolib
    rpath_allowlist:
      - "**"
    binary_relocation:
      - "**/redshift/redshift4houdini/**/dso/*.so"
    missing_dso_allowlist:
      - "**"

tests:
  - script:
    - $REDSHIFT_COREDATAPATH/bin/redshiftCmdLine -listrenderoptions

about:
  homepage: https://redshift.maxon.net
  summary: >
    3D computer animation, modeling, simulation, and rendering software
