# Recipe in conda-build format.

# See https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html for information
# about this file.

{% set version = "2026.0" %}
{% set major_version = "2026" %}
{% set minor_version = "0" %}

package:
  name: maya
  version: {{ version }}

source:
  url: archive_files/Autodesk_Maya_{{ major_version }}_Linux_64bit.tgz
  sha256: d3e8cc63ea573383eb02046398a9f49c26cb55708eb8fb6266d04c46a5d6a48e
  folder: installer

build:
  number: 0
  detect_binary_files_with_prefix: false
  binary_relocation: false
  missing_dso_whitelist:
    - "**"

requirements:
  build:
    - patchelf

test:
  commands:
    - mayapy --help
    - mayapy -c 'import maya; import maya.standalone; import maya.OpenMaya as om1; import maya.api.OpenMaya as om2; maya.standalone.initialize(); print("Hello from mayapy"); maya.standalone.uninitialize()'
    - maya -batch -command 'print "Hello from maya -batch"; quit -exitCode 0 -force'

about:
  home: https://www.autodesk.com/products/maya/overview
  license: LicenseRef-AutodeskEULA
  summary: Maya is professional 3D software for creating realistic characters and blockbuster-worthy effects.
