# Recipe in rattler-build format.
# See https://prefix-dev.github.io/rattler-build/latest/

context:
  nerfstudio_git_rev: "73fe54dda0b743616854fc839889d955522e0e68"
  # The "post20" in the version is based on:
  #   $ git rev-list v1.1.5..73fe54dda0b743616854fc839889d955522e0e68 --count
  #   20
  version: "1.1.5.post20"

  # NeRF Studio dependencies installed from source
  tinycudann_git_rev: "075158a70b87dba8729188a9cadc9411cfa4b71d"
  gsplat_git_rev: "640a4fe546f5cadd8835acf259fce9a672ffecf4"
  nerfview_git_rev: "cfea14812094594287a00af425eebd2a5cd87076"
  fusedssim_git_rev: "30fb258c8a38fe61e640c382f891f14b2e8b0b5a"
  splatfactow_git_rev: "119a3bfb3aa03669278e174ff11c4dfdcbcf97d7"

package:
  name: nerfstudio
  version: ${{ version }}

source:
  - git: https://github.com/nerfstudio-project/nerfstudio.git
    rev: "${{nerfstudio_git_rev}}"
    target_directory: nerfstudio
  - git: https://github.com/NVlabs/tiny-cuda-nn.git
    rev: "${{tinycudann_git_rev}}"
    target_directory: tinycudann
  - git: https://github.com/nerfstudio-project/gsplat.git
    rev: "${{gsplat_git_rev}}"
    target_directory: gsplat
  - git: https://github.com/hangg7/nerfview.git
    rev: "${{nerfview_git_rev}}"
    target_directory: nerfview
  - git: https://github.com/rahul-goel/fused-ssim.git
    rev: "${{fusedssim_git_rev}}"
    target_directory: fusedssim
    # TODO: Switch pycolmap to the official upstream project (needs change in gsplat)
  - git: https://github.com/rmbrualla/pycolmap.git
    rev: "cc7ea4b7301720ac29287dbe450952511b32125e"
    target_directory: pycolmap
  - git: https://github.com/KevinXu02/splatfacto-w.git
    rev: "${{splatfactow_git_rev}}"
    target_directory: splatfacto-w

build:
  number: 0
  dynamic_linking:
    # Selectively apply binary relocation, avoiding ones added via 'pip install'
    # In particular, pymeshlab from PyPI includes a Qt5 that is incompatible
    # with conda-forge's Qt5, and this avoids prepending $CONDA_PREFIX/lib
    # to that meshlab rpath so that the overall package works anyway.
    binary_relocation:
      - "**/site-packages/gsplat/*.so"
      - "**/site-packages/tinycudann_bindings/*.so"

requirements:
  host:
    - python
    - pip
    - ${{ compiler('cuda') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - cuda-toolkit

    # The old pycolmap dependency of gsplat simple_trainer is not compatible with NumPy 2
    - numpy <2

    ## From nerfstudio
    - appdirs >=1.4,<1.5
    - av >=14.2,<14.3
    # - comet-ml >=3.33.8
    - cryptography >=43
    # conda-forge had tyro 0.9.1, the pip installs wanted 0.9.17
    # - tyro >=0.9,<0.10
    # - python-ninja >=1.10
    - gdown >=5.2,<5.3
    - h5py >=3.13,<3.14
    - imageio >=2.37,<2.38
    - ipywidgets >=8.1,<8.2
    # conda-forge version of jaxtyping pulled in an old version of typeguard, pip install wanted newer one
    # - jaxtyping >=0.2.36,<0.2.37
    - jupyterlab >=4.3,<4.4
    - matplotlib >=3.10,<3.11
    - mediapy >=1.2,<1.3
    - msgpack-python >=1.1,<1.2
    - msgpack-numpy >=0.4.8,<0.4.9
    # - nerfacc ==0.5.2
    # - opencv-python-headless ==4.10.0.84
    - open3d >=0.19,<0.20
    - pillow >=11.1,<11.2
    - plotly >=6.0,<6.1
    - protobuf >=5.28,<5.29
    - pyngrok >=7.2,<7.3
    - python-socketio >=5.11,<5.12
    - pyquaternion >=0.9.9,<0.10
    - requests >=2.32,<2.33
    - rich >=13.9,<13.10
    - scikit-image >=0.25.2,<0.25.3
    - splines >=0.3.2,<0.3.3
    - tensorboard >=2.19,<2.20
    - pytorch-gpu >=2.6,<2.7
    - torchvision >=0.21,<0.22
    - torchmetrics >=1.6,<1.7
    - typing_extensions >=4.12,<4.13
    # - viser ==0.2.7
    # - nuscenes-devkit >=1.1.1
    - wandb >=0.19,<0.20
    # - xatlas
    - trimesh >=4.6,<4.7
    - timm >=1.0,<1.1
    # - gsplat ==1.4.0
    - pytorch-msssim >=1.0,<1.1
    - pathos >=0.3.3,<0.3.4
    - packaging >=24.2,<24.3
    # - fpsample
    - tensorly >=0.8.1,<0.8.2
    # - rawpy >=0.18.1
    # - pymeshlab >=2022.2

    ## From tyro
    - typeguard >=4.4.2

    ## From gsplat simple_trainer.py
#    - pycolmap
    - imageio-ffmpeg >=0.6,<0.7
    - psutil >=7.0,<7.1

    ## From viser
    - websockets >=15.0,<15.1
    - msgspec >=0.19.0,<0.20
    - nodeenv >=1.9,<1.10
    - yourdfpy >=0.0.57,<0.1
    - plyfile >=1.1,<1.2

    ## From everett[ini]
    - everett >=3.1,<3.2
    - configobj >=5.0.9,<5.1

    ## From commet-ml
    - dulwich >=0.22,<0.23
#    - python-box >=6.1,<7.0 # conda-forge only has version 7+ with recent Pythons
    - requests-toolbelt >=1.0,<1.1
    - semantic_version >=2.10,<2.11
    - simplejson >=3.20,<3.21
    - wrapt >=1.17,<1.18
    - wurlitzer >=3.1.1,<3.2

    ## From nuscenes-devkit
    - cachetools >=5.5,<5.6
    - descartes >= 1.1,<1.2
    - fire >=0.7.0,<0.7.1
    - py-opencv >=4.11,<4.12
    - scikit-learn >=1.6,<1.7
    - shapely >=2.0,<2.1
    - pycocotools >=2.0,<2.1
    - jupyter >=1.1,<1.2

    ## From torchmetrics[image]
    - torch-fidelity >=0.3,<0.4

    ## From trimesh[easy]
    - colorlog >=6.9,<6.10
    # - manifold3d >=2.3.0
    - chardet >=5.2,<5.3
    - svg.path >=6.3,<6.4
    - pycollada >=0.9,<0.10
    - rtree >=1.4,<1.5
    - python-xxhash >=3.5,<3.6
    # - embreex
    # - vhacdx
    - mapbox_earcut >=1.0.3,<1.1

    ## From splatfacto-w
    - pandas >=2.2,<2.3
  run:
    - python
    - cuda-cudart

    # The old pycolmap dependency of gsplat simple_trainer is not compatible with NumPy 2
    - numpy <2

    ## From nerfstudio
    - appdirs >=1.4,<1.5
    - av >=14.2,<14.3
    # - comet-ml >=3.33.8
    - cryptography >=43
    # conda-forge had tyro 0.9.1, the pip installs wanted 0.9.17
    # - tyro >=0.9,<0.10
    # - python-ninja >=1.10
    - gdown >=5.2,<5.3
    - h5py >=3.13,<3.14
    - imageio >=2.37,<2.38
    - ipywidgets >=8.1,<8.2
    # conda-forge version of jaxtyping pulled in an old version of typeguard, pip install wanted newer one
    # - jaxtyping >=0.2.36,<0.2.37
    - jupyterlab >=4.3,<4.4
    - matplotlib >=3.10,<3.11
    - mediapy >=1.2,<1.3
    - msgpack-python >=1.1,<1.2
    - msgpack-numpy >=0.4.8,<0.4.9
    # - nerfacc ==0.5.2
    # - opencv-python-headless ==4.10.0.84
    - open3d >=0.19,<0.20
    - pillow >=11.1,<11.2
    - plotly >=6.0,<6.1
    - protobuf >=5.28,<5.29
    - pyngrok >=7.2,<7.3
    - python-socketio >=5.11,<5.12
    - pyquaternion >=0.9.9,<0.10
    - requests >=2.32,<2.33
    - rich >=13.9,<13.10
    - scikit-image >=0.25.2,<0.25.3
    - splines >=0.3.2,<0.3.3
    - tensorboard >=2.19,<2.20
    - pytorch-gpu >=2.6,<2.7
    - torchvision >=0.21,<0.22
    - torchmetrics >=1.6,<1.7
    - typing_extensions >=4.12,<4.13
    # - viser ==0.2.7
    # - nuscenes-devkit >=1.1.1
    - wandb >=0.19,<0.20
    # - xatlas
    - trimesh >=4.6,<4.7
    - timm >=1.0,<1.1
    # - gsplat ==1.4.0
    - pytorch-msssim >=1.0,<1.1
    - pathos >=0.3.3,<0.3.4
    - packaging >=24.2,<24.3
    # - fpsample
    - tensorly >=0.8.1,<0.8.2
    # - rawpy >=0.18.1
    # - pymeshlab >=2022.2

    ## From tyro
    - typeguard >=4.4.2

    ## From gsplat simple_trainer.py
#    - pycolmap
    - imageio-ffmpeg >=0.6,<0.7
    - psutil >=7.0,<7.1

    ## From viser
    - websockets >=15.0,<15.1
    - msgspec >=0.19.0,<0.20
    - nodeenv >=1.9,<1.10
    - yourdfpy >=0.0.57,<0.1
    - plyfile >=1.1,<1.2

    ## From everett[ini]
    - everett >=3.1,<3.2
    - configobj >=5.0.9,<5.1

    ## From commet-ml
    - dulwich >=0.22,<0.23
#    - python-box >=6.1,<7.0 # conda-forge only has version 7+ with recent Pythons
    - requests-toolbelt >=1.0,<1.1
    - semantic_version >=2.10,<2.11
    - simplejson >=3.20,<3.21
    - wrapt >=1.17,<1.18
    - wurlitzer >=3.1.1,<3.2

    ## From nuscenes-devkit
    - cachetools >=5.5,<5.6
    - descartes >= 1.1,<1.2
    - fire >=0.7.0,<0.7.1
    - py-opencv >=4.11,<4.12
    - scikit-learn >=1.6,<1.7
    - shapely >=2.0,<2.1
    - pycocotools >=2.0,<2.1
    - jupyter >=1.1,<1.2

    ## From torchmetrics[image]
    - torch-fidelity >=0.3,<0.4

    ## From trimesh[easy]
    - colorlog >=6.9,<6.10
    # - manifold3d >=2.3.0
    - chardet >=5.2,<5.3
    - svg.path >=6.3,<6.4
    - pycollada >=0.9,<0.10
    - rtree >=1.4,<1.5
    - python-xxhash >=3.5,<3.6
    # - embreex
    # - vhacdx
    - mapbox_earcut >=1.0.3,<1.1

    ## From splatfacto-w
    - pandas >=2.2,<2.3

    ## Needed by splatfacto in nerfstudio because it uses torch CUDA jitting
    - ${{ compiler('cuda') }}
    - cuda-toolkit

tests:
- script:
  - python -c "import tinycudann"
  - python -c "import gsplat"
  - python -c "import pymeshlab"
  - ns-download-data --help
  - ns-process-data --help
  - ns-train --help
  - ns-train splatfacto --help
  - ns-train splatfacto-w --help
  - ns-train splatfacto-w-light --help
  - ns-export --help
  - ns-export gaussian-splat --help
  - ns-viewer --help
  - gsplat_simple_trainer --help
  - gsplat_simple_trainer mcmc --help

about:
  homepage: https://docs.nerf.studio/
  license: Apache-2.0
  summary: >
    Nerfstudio provides a simple API that allows for a simplified end-to-end process of creating, training,
    and testing NeRFs. The library supports a more interpretable implementation of NeRFs by modularizing
    each component. With more modular NeRFs, we hope to create a more user-friendly experience in exploring
    the technology.
