
package:
  name: cinema4d-vray
  version: "2025"

source:
- path: ../../archive_files/cinema4d-vray-2025/win-64 # [win64]

build:
  number: 0
  binary_relocation: false
  detect_binary_files_with_prefix: false
  ignore_prefix_files: true
  missing_dso_whitelist:
    - "**"

requirements:
  run:
    - cinema4d >=2025

about:
  homepage: https://www.chaos.com/vray/maya
  documentation: https://docs.chaos.com/display/VMAYA
  license: LicenseRef-ChaosEULA
  summary: |
    V-Ray is a 3D photorealistic ray-traced rendering plug-in.
    V-Ray for Maya is a 3D rendering plugin for Maya that's used to create visual effects and animations for film, television, and other industries.
