context:
  version_partial: "16.0"
  version_minor: "1"

package:
  name: nuke
  version: ${{ version_partial + "." + version_minor }}

source:
  url: file://archive_files/Nuke{{ version_partial }}v{{ version_minor }}-linux-x86_64.tgz
  sha256: 61b570ea6d4f8a7e2f0647952c8e039fc02df6f6649e9de1d2ee0543398ed92f
  target_directory: installer

build:
  number: 0
  dynamic_linking:
    binary_relocation: False
    missing_dso_allowlist:
    - "*"
  prefix_detection:
    ignore_binary_files: True
  # The binary is built to be relocatable, so can ignore the warnings about DSOs.
  
about:
  homepage: https://www.foundry.com/products/nuke-family/nuke
  license: LicenseRef-FoundryEULA
  summary: Nuke is the powerful node-based compositing tool at the heart of the Nuke family.
