# Recipe in rattler-build format.
# See https://prefix-dev.github.io/rattler-build/latest/

context:
  version: "2026.0"
  major_version: "2026"
  minor_version: "0"

package:
  name: maya-mtoa
  version: ${{ version }}

source:
  path: ../../archive_files/Autodesk_Maya_${{ major_version }}_ML_Linux_64bit.tgz
  sha256: d3e8cc63ea573383eb02046398a9f49c26cb55708eb8fb6266d04c46a5d6a48e
  target_directory: installer

build:
  number: 0
  # These build options for repackaging an application
  # https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html
  prefix_detection:
    ignore_binary_files: True
  dynamic_linking:
    binary_relocation: False
    missing_dso_allowlist:
    - "**"

requirements:
  build:
    - maya ${{ version }}.*
  run:
    - maya ${{ version }}.*

tests:
  - script:
    # Maya's Python interpreter
    - mayapy --help
    # Confirm that the mtoa plugin is available in mayapy
    # - mayapy -c 'import maya.standalone; maya.standalone.initialize(); import mtoa; from maya.cmds import arnoldRender; print("Hello from mayapy"); print(dir(mtoa)); maya.standalone.uninitialize()'
    - mayapy -c 'import maya.standalone; maya.standalone.initialize(); import mtoa; print("Hello from mayapy"); print(dir(mtoa)); maya.standalone.uninitialize()'
    # The maya -batch command
    - maya -batch -command 'print "Hello from maya -batch"; quit -exitCode 0 -force'


about:
  homepage: https://www.autodesk.com/products/maya/overview
  license: LicenseRef-AutodeskEULA
  summary: Maya is professional 3D software for creating realistic characters and blockbuster-worthy effects.
