# Recipe in rattler-build format.
# See https://prefix-dev.github.io/rattler-build/latest/

context:
  version: "0.15.13"

package:
  name: maya-openjd
  version: ${{ version }}

# This source reference uses the source archive published to PyPI
source:
  url: https://pypi.io/packages/source/d/deadline-cloud-for-maya/deadline_cloud_for_maya-${{ version }}.tar.gz
  sha256: d178df5d28e94a21dbcdc0936b2cf8c29c646e79aa2b2bd53165c9429b99c2e2

build:
  number: 0
  script:
    - python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python
    - deadline >=0.52,<0.55
    - openjd-adaptor-runtime 0.9.*

tests:
- python:
    imports:
      - deadline.maya_adaptor
- requirements:
    run:
      - pip
  script:
    - pip check
# This doesn't work on Windows, possibly a rattler-build bug since maya-openjd.exe is in $PREFIX/Scripts
#    - maya-openjd --help

about:
  summary: AWS Deadline Cloud for Maya
  homepage: https://github.com/aws-deadline/deadline-cloud-for-maya
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
