# Recipe in rattler-build format.
# See https://prefix-dev.github.io/rattler-build/latest/

context:
  version: "0.54.3"

package:
  name: deadline
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/d/deadline/deadline-${{ version }}.tar.gz
  sha256: 9cd40fde120ae2600717d2be403b2ce6b9feac2a1c5b9ff290af3f318d1e8796

build:
  number: 0
  script:
    - python -m pip install . -vv --no-deps

requirements:
  host:
    - python
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python
    - boto3 >=1.42.29
    - click >=8.1.7
    - pyyaml >=6.0
    - typing-extensions >=4.8
    - python-xxhash >=3.4,<3.7
    - ${{ "pywin32 >=307,<311" if win }}
    - qtpy 2.4.*
    - psutil >=7

tests:
- python:
    imports:
      - deadline
      - deadline.client
      - deadline.job_attachments
- requirements:
    run:
      - pip
  script:
  - pip check
  - python -m deadline --help
# This doesn't work on Windows, possibly a rattler-build bug since deadline.exe is in $PREFIX/Scripts
#  - deadline --help

about:
  summary: Multi-purpose library and command line tool that implements functionality to support applications using AWS Deadline Cloud.
  homepage: https://github.com/aws-deadline/deadline-cloud
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
