#!/usr/bin/env bash
#
# This script finds the Python that is used by the Deadline Cloud CLI,
# and then runs submit-package-job-script.py with that Python.

set -euo pipefail


DEADLINE_PATH=$(which deadline)
if [ $(basename $(dirname $DEADLINE_PATH)) = Scripts ]; then
    # Windows Python installation with Scripts directory
    DEADLINE_PYTHON=$(dirname $(dirname $DEADLINE_PATH))/Python.exe
else
    # Take the #! from the script
    DEADLINE_PYTHON=$(head -1 $DEADLINE_PATH | cut -c 3-)
fi

# Run the Python script submitter with the same Python
$DEADLINE_PYTHON $0-script.py "$@"
