# Recipe in rattler-build format.
# See https://prefix-dev.github.io/rattler-build/latest/

context:
  version: "1.0"

package:
  name: blender-plugin-build
  version: ${{ version }}

source:
  - if: linux
    then:
      # This zip file contains any number of Blender addons. 
      url: file://archive_files/blender-plugins.zip
      sha256: PLACEHOLDER_SHA
      target_directory: plugins

build:
  number: 0
  # These build options for repackaging an application
  # https://prefix-dev.github.io/rattler-build/latest/build_options/#prefix-detection-replacement-options
  prefix_detection:
    ignore_binary_files: True
  # https://prefix-dev.github.io/rattler-build/latest/build_options/#dynamic-linking-configuration
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      - "**"

requirements:
  run:
    - blender

tests:
  - script:
    - |
      cat <<EOF > test.py
      import bpy
      for addon in bpy.context.preferences.addons:
          print(addon)
      EOF
    - blender --background --python test.py

about:
  license: LicenseRef-Multiple
  summary: This package contains multiple Blender plugins provided in a zip archive.