#!/usr/bin/env python3
"""Generate the human-browsable sample index from sample_catalog.json."""

from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from typing import Any, Iterable

from catalog_lib import GENERATED_PATH, load_catalog, taxonomy_labels

HEADER = """# AWS Deadline Cloud sample catalog

> This file is generated by `python3 scripts/generate_samples.py`. Edit
> [`sample_catalog.json`](sample_catalog.json), not this file, then regenerate it.

Find a sample by what you want to accomplish. Paths in the catalog are stable sample
identities; samples remain in their existing directories.
"""


def sample_line(sample: dict[str, Any]) -> str:
    details: list[str] = []
    if sample.get("platforms"):
        details.append("platforms: " + ", ".join(sample["platforms"]))
    if sample.get("tags"):
        details.append("tags: " + ", ".join(sample["tags"]))
    suffix = f" _({' · '.join(details)})_" if details else ""
    return f"* **[{sample['title']}]({sample['path']})** — {sample['description']}{suffix}"


def render_group(title: str, samples: Iterable[dict[str, Any]], empty: str = "No samples.") -> list[str]:
    ordered = sorted(samples, key=lambda sample: (sample["title"].casefold(), sample["path"]))
    lines = [f"## {title}", ""]
    lines.extend(sample_line(sample) for sample in ordered)
    if not ordered:
        lines.append(empty)
    lines.append("")
    return lines


def render(catalog: dict[str, Any]) -> str:
    samples = catalog["samples"]
    category_labels = taxonomy_labels(catalog, "categories")
    task_labels = taxonomy_labels(catalog, "tasks")
    journey_labels = taxonomy_labels(catalog, "journeys")
    lines = [HEADER.rstrip(), ""]

    lines.extend(render_group("Featured samples", (sample for sample in samples if sample.get("featured"))))

    recent = sorted(
        (sample for sample in samples if sample.get("updated")),
        key=lambda sample: (sample["updated"], sample["title"].casefold()),
        reverse=True,
    )[:12]
    lines.extend(
        [
            "## Recent highlights",
            "",
            "This is a curated selection of noteworthy additions and updates, not an exhaustive chronology.",
            "",
        ]
    )
    for sample in recent:
        lines.append(f"* **{sample['updated']} — [{sample['title']}]({sample['path']})** — {sample['description']}")
    lines.append("")

    by_task: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for sample in samples:
        for task in sample["tasks"]:
            by_task[task].append(sample)
    lines.extend(["## Browse by goal", ""])
    lines.append("Each sample can appear under more than one goal.")
    lines.append("")
    for task in task_labels:
        lines.extend(render_group(task_labels[task], by_task[task]))

    by_category: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for sample in samples:
        by_category[sample["category"]].append(sample)
    lines.extend(["# Browse by sample type", ""])
    for category in category_labels:
        lines.extend(render_group(category_labels[category], by_category[category]))

    by_journey: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for sample in samples:
        for journey in sample.get("journeys", []):
            by_journey[journey].append(sample)
    lines.extend(["# Browse by journey", ""])
    lines.append("See [`docs/sample-navigation.md`](docs/sample-navigation.md) for abbreviated decision guidance.")
    lines.append("")
    for journey in journey_labels:
        lines.extend(render_group(journey_labels[journey], by_journey[journey]))

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if SAMPLES.md is not current")
    args = parser.parse_args()
    generated = render(load_catalog())
    if args.check:
        current = GENERATED_PATH.read_text(encoding="utf-8") if GENERATED_PATH.exists() else ""
        if current != generated:
            print("SAMPLES.md is out of date; run: python3 scripts/generate_samples.py", file=sys.stderr)
            return 1
        print("SAMPLES.md is current")
        return 0
    GENERATED_PATH.write_text(generated, encoding="utf-8")
    print(f"Wrote {GENERATED_PATH.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
