# Recipe in rattler-build format.
# See https://prefix-dev.github.io/rattler-build/latest/

context:
  version: "21.0.440"

package:
  name: houdini
  version: ${{ version }}

source:
  - if: linux
    then:
      url: file://archive_files/houdini-{{ version }}-linux_x86_64_gcc11.2.tar.gz
      sha256: a87451f9146d52051a9ba142d535936638351526a48cba0c6156a221f3be58e6
      target_directory: installer

build:
  number: 0
  # These build options for repackaging an application
  # https://prefix-dev.github.io/rattler-build/latest/build_options/#prefix-detection-replacement-options
  prefix_detection:
    ignore_binary_files: True
  # https://prefix-dev.github.io/rattler-build/latest/build_options/#dynamic-linking-configuration
  dynamic_linking:
    binary_relocation: False

requirements:
  build:
    - patchelf

tests:
  - script:
    - houdini -h
    - hython -h

about:
  homepage: https://www.sidefx.com/products/houdini/
  license: LicenseRef-SideFXEULA
  summary: >
    Houdini is built from the ground up to be a procedural system that empowers artists to work freely,
    create multiple iterations and rapidly share workflows with colleagues.