# Recipe in rattler-build format.
# See https://prefix-dev.github.io/rattler-build/latest/

context:
  bucket_name: '${{ env.get("BUILD_BUCKET", default="conda-build-artifacts-657566733920-us-west-2") }}'
  version_partial: "21.0"
  version_minor: "596"
  gcc_version: "gcc11.2"
  version: ${{version_partial}}.${{version_minor}}

package:
  name: houdini
  version: ${{ version }}

source:
  - if: linux
    then:
      url: s3://${{ bucket_name }}/source-artifacts/houdini/${{ version_partial }}/houdini-${{ version_partial }}.${{ version_minor }}-linux_x86_64_${{ gcc_version }}.tar.gz
      target_directory: installer

build:
  number: 2
  script:
    - if: unix
      then:
        - bash $RECIPE_DIR/build.sh
  prefix_detection:
    ignore_binary_files: true
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      - "**"

requirements:
  build:
    - patchelf

about:
  homepage: https://www.sidefx.com/products/houdini/
  license: LicenseRef-SideFXEULA
  summary: >
    Houdini is built from the ground up to be a procedural system that empowers artists to work freely,
    create multiple iterations and rapidly share workflows with colleagues.
