# Recipe in rattler-build format.
# See https://prefix-dev.github.io/rattler-build/latest/
# This release requires deadline 0.59.x and openjd-adaptor-runtime 0.7.x-0.9.x
# in the target channel. The standalone deadline sample may track a newer,
# incompatible minor release.

context:
  version: "0.11.4"

package:
  name: cinema4d-openjd
  version: ${{ version }}

# This source reference uses the source archive published to PyPI
source:
  url: https://pypi.io/packages/source/d/deadline-cloud-for-cinema-4d/deadline_cloud_for_cinema_4d-${{ version }}.tar.gz
  sha256: 474830446bd67adffa6d435dd8dbf7b37993486c268a42d8949d632747977427

build:
  number: 0
  script:
    - python -m pip install . -vv --no-deps
  python:
    entry_points:
      - cinema4d-openjd = deadline.cinema4d_adaptor.Cinema4DAdaptor:main

requirements:
  host:
    - python
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python
    - deadline >=0.59,<0.60
    - openjd-adaptor-runtime >=0.7,<0.10
    - ${{ "fonttools >=4.59.2,<4.64" if win }}

tests:
- python:
    imports:
      - deadline.cinema4d_adaptor
- requirements:
    run:
      - pip
  script:
    - pip check
    - cinema4d-openjd --help

about:
  summary: AWS Deadline Cloud for Cinema 4D
  homepage: https://github.com/aws-deadline/deadline-cloud-for-cinema-4d
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
